// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserDepRelation = "user_dep_relations"

// UserDepRelation 用户和部门关系表
type UserDepRelation struct {
	UserID int32 `gorm:"column:user_id;comment:用户ID" json:"user_id"` // 用户ID
	DepID  int32 `gorm:"column:dep_id;comment:部门ID" json:"dep_id"`   // 部门ID
}

// TableName UserDepRelation's table name
func (*UserDepRelation) TableName() string {
	return TableNameUserDepRelation
}
