// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID           int32          `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户ID，自增主键" json:"user_id"`                                                              // 用户ID，自增主键
	Username         string         `gorm:"column:username;not null;comment:用户名，不能为空" json:"username"`                                                                                  // 用户名，不能为空
	Email            string         `gorm:"column:email;comment:电子邮箱地址，唯一索引" json:"email"`                                                                                              // 电子邮箱地址，唯一索引
	Password         string         `gorm:"column:password;not null;comment:加密后的密码，长度一般为哈希后的结果，不能为空" json:"password"`                                                                   // 加密后的密码，长度一般为哈希后的结果，不能为空
	AccountType      string         `gorm:"column:account_type;default:regular;comment:账号类型：普通用户、auth用户、管理员用户，默认为普通用户" json:"account_type"`                                             // 账号类型：普通用户、auth用户、管理员用户，默认为普通用户
	AuthProvider     string         `gorm:"column:auth_provider;comment:OAuth提供商名称，如Google、Twitter等" json:"auth_provider"`                                                              // OAuth提供商名称，如Google、Twitter等
	AuthUserID       string         `gorm:"column:auth_user_id;comment:用户在OAuth提供商系统中的唯一标识符" json:"auth_user_id"`                                                                       // 用户在OAuth提供商系统中的唯一标识符
	AuthAccessToken  string         `gorm:"column:auth_access_token;comment:OAuth访问令牌" json:"auth_access_token"`                                                                        // OAuth访问令牌
	AuthRefreshToken string         `gorm:"column:auth_refresh_token;comment:OAuth刷新令牌" json:"auth_refresh_token"`                                                                      // OAuth刷新令牌
	AuthUserInfo     string         `gorm:"column:auth_user_info;comment:OAuth提供商返回的用户信息，JSON格式" json:"auth_user_info"`                                                                 // OAuth提供商返回的用户信息，JSON格式
	Balance          float64        `gorm:"column:balance;default:0.00;comment:用户余额，DECIMAL类型，精确到小数点后两位，默认为0.00" json:"balance"`                                                        // 用户余额，DECIMAL类型，精确到小数点后两位，默认为0.00
	Source           string         `gorm:"column:source;comment:用户来源信息，如Twitter等平台" json:"source"`                                                                                     // 用户来源信息，如Twitter等平台
	Status           string         `gorm:"column:status;default:active;comment:用户状态，active为激活状态，inactive为未激活状态，frozen为已冻结状态，suspended为已暂停状态，deleted为已删除状态，默认为active" json:"status"`    // 用户状态，active为激活状态，inactive为未激活状态，frozen为已冻结状态，suspended为已暂停状态，deleted为已删除状态，默认为active
	GoogleAuthKey    string         `gorm:"column:google_auth_key;comment:用户Google Authenticator的密钥" json:"google_auth_key"`                                                            // 用户Google Authenticator的密钥
	TwoFactorAuth    string         `gorm:"column:two_factor_auth;default:disabled;comment:用户两步验证状态，enabled为已启用，disabled为已禁用，默认为disabled" json:"two_factor_auth"`                       // 用户两步验证状态，enabled为已启用，disabled为已禁用，默认为disabled
	KycStatus        string         `gorm:"column:kyc_status;default:pending;comment:KYC（Know Your Customer）状态，pending为待审核，approved为已审核通过，rejected为审核未通过，默认为pending" json:"kyc_status"` // KYC（Know Your Customer）状态，pending为待审核，approved为已审核通过，rejected为审核未通过，默认为pending
	CreatedAt        time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:记录创建时间，默认为当前时间" json:"created_at"`                                                       // 记录创建时间，默认为当前时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:记录更新时间，默认为当前时间，自动更新" json:"updated_at"`                                                  // 记录更新时间，默认为当前时间，自动更新
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:记录删除时间，用于软删除，为空表示未删除" json:"deleted_at"`                                                                           // 记录删除时间，用于软删除，为空表示未删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
