// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"GoLib/GORM/model"
)

func newDep(db *gorm.DB, opts ...gen.DOOption) dep {
	_dep := dep{}

	_dep.depDo.UseDB(db, opts...)
	_dep.depDo.UseModel(&model.Dep{})

	tableName := _dep.depDo.TableName()
	_dep.ALL = field.NewAsterisk(tableName)
	_dep.ID = field.NewInt32(tableName, "id")
	_dep.Name = field.NewString(tableName, "name")
	_dep.Num = field.NewInt32(tableName, "num")

	_dep.fillFieldMap()

	return _dep
}

type dep struct {
	depDo depDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String
	Num  field.Int32

	fieldMap map[string]field.Expr
}

func (d dep) Table(newTableName string) *dep {
	d.depDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dep) As(alias string) *dep {
	d.depDo.DO = *(d.depDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dep) updateTableName(table string) *dep {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.Name = field.NewString(table, "name")
	d.Num = field.NewInt32(table, "num")

	d.fillFieldMap()

	return d
}

func (d *dep) WithContext(ctx context.Context) *depDo { return d.depDo.WithContext(ctx) }

func (d dep) TableName() string { return d.depDo.TableName() }

func (d dep) Alias() string { return d.depDo.Alias() }

func (d dep) Columns(cols ...field.Expr) gen.Columns { return d.depDo.Columns(cols...) }

func (d *dep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dep) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 3)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["num"] = d.Num
}

func (d dep) clone(db *gorm.DB) dep {
	d.depDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dep) replaceDB(db *gorm.DB) dep {
	d.depDo.ReplaceDB(db)
	return d
}

type depDo struct{ gen.DO }

func (d depDo) Debug() *depDo {
	return d.withDO(d.DO.Debug())
}

func (d depDo) WithContext(ctx context.Context) *depDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d depDo) ReadDB() *depDo {
	return d.Clauses(dbresolver.Read)
}

func (d depDo) WriteDB() *depDo {
	return d.Clauses(dbresolver.Write)
}

func (d depDo) Session(config *gorm.Session) *depDo {
	return d.withDO(d.DO.Session(config))
}

func (d depDo) Clauses(conds ...clause.Expression) *depDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d depDo) Returning(value interface{}, columns ...string) *depDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d depDo) Not(conds ...gen.Condition) *depDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d depDo) Or(conds ...gen.Condition) *depDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d depDo) Select(conds ...field.Expr) *depDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d depDo) Where(conds ...gen.Condition) *depDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d depDo) Order(conds ...field.Expr) *depDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d depDo) Distinct(cols ...field.Expr) *depDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d depDo) Omit(cols ...field.Expr) *depDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d depDo) Join(table schema.Tabler, on ...field.Expr) *depDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d depDo) LeftJoin(table schema.Tabler, on ...field.Expr) *depDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d depDo) RightJoin(table schema.Tabler, on ...field.Expr) *depDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d depDo) Group(cols ...field.Expr) *depDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d depDo) Having(conds ...gen.Condition) *depDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d depDo) Limit(limit int) *depDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d depDo) Offset(offset int) *depDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d depDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *depDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d depDo) Unscoped() *depDo {
	return d.withDO(d.DO.Unscoped())
}

func (d depDo) Create(values ...*model.Dep) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d depDo) CreateInBatches(values []*model.Dep, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d depDo) Save(values ...*model.Dep) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d depDo) First() (*model.Dep, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dep), nil
	}
}

func (d depDo) Take() (*model.Dep, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dep), nil
	}
}

func (d depDo) Last() (*model.Dep, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dep), nil
	}
}

func (d depDo) Find() ([]*model.Dep, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dep), err
}

func (d depDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dep, err error) {
	buf := make([]*model.Dep, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d depDo) FindInBatches(result *[]*model.Dep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d depDo) Attrs(attrs ...field.AssignExpr) *depDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d depDo) Assign(attrs ...field.AssignExpr) *depDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d depDo) Joins(fields ...field.RelationField) *depDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d depDo) Preload(fields ...field.RelationField) *depDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d depDo) FirstOrInit() (*model.Dep, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dep), nil
	}
}

func (d depDo) FirstOrCreate() (*model.Dep, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dep), nil
	}
}

func (d depDo) FindByPage(offset int, limit int) (result []*model.Dep, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d depDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d depDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d depDo) Delete(models ...*model.Dep) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *depDo) withDO(do gen.Dao) *depDo {
	d.DO = *do.(*gen.DO)
	return d
}
